name: oasismove

channels:
  - conda-forge

dependencies:
  - fenics
  - pip
  - python >=3.8
  - git
  - matplotlib
  - scipy
  - pip:
      - cppimport
      - git+https://github.com/mikaem/fenicstools

